# Generated by Django 2.1.5 on 2019-02-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='btcpay_item_name',
        ),
    ]
