# Generated by Django 2.1.5 on 2019-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190205_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
