# Generated by Django 2.1.5 on 2019-02-06 14:28

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_path',
            field=models.FileField(null=True, upload_to=item.models.shop_directory_path),
        ),
    ]
